### ISSUE TITLE
Will U plz tell me how to Run the baker exactely :(

### ISSUE THREAD

**Issue by zmfrog** [FunsTW/VertexAnimationBaker_Muilt-Rows#1]
Thank U for share! god work! but  eider U nor sugi-cho explain how to make backer work, I spend tans of time to guess over and over again，then still....Cry out

**Comment by FuRanSuTW** [comment]
I modified it from [this project](https://github.com/chenjd/Render-Crowd-Of-Animated-Characters)
Maybe you can try to understand how to use the project first

**Comment by zmfrog** [comment]
Well，blank result ，but thank u anyway ：D
